version: "3"

services:
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build: ./docker-assets/nginx
        volumes:
            - ./src:/src
            - ./docker-assets/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php-fpm
        ports:
            - 8080:8080
        working_dir: /src

    php-fpm:
        container_name: ${PROJECT_NAME}_php-fpm
        build: ./docker-assets/php
        links:
            - mysql
            - redis
            - mailhog
        volumes:
            - ./src:/src
            - ./docker-assets/php/xdebug.ini:/usr/local/etc/php/php.ini
        working_dir: /src

    frontend:
        container_name: ${PROJECT_NAME}_frontend
        build:
            context: .
            dockerfile: docker-assets/frontend/Dockerfile
        volumes:
            - ./frontend:/var/www/html/frontend
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=development
        command: sh -c 'cd frontend && npm run start'

    mysql:
        container_name: ${PROJECT_NAME}_mysql
        image: mysql:8.0
        volumes: 
            - ./database:/var/lib/mysql
            - ./docker-assets/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3305:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:alpine

    mailhog:
        container_name: ${PROJECT_NAME}_mailhog
        image: mailhog/mailhog
        ports: 
            - 1025:1025
            - 6082:8025
    
