openapi: 3.0.0
info:
  title: 'Vetiq API'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
paths:
  /hospital/login:
    post:
      tags:
        - Hospital
      summary: ログイン
      operationId: e536880aed23ff421f6e6cd08e14ff4d
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Requests~1Hospital~1LoginRequest'
      responses:
        '200':
          description: ログイン成功
        '401':
          description: ログイン失敗
  /hospital/logout:
    post:
      tags:
        - Hospital
      summary: ログアウト
      operationId: e8b5787dbac0ed48bbc31ee8b3c29918
      responses:
        '200':
          description: ログアウト成功
  /hospital/info:
    get:
      tags:
        - Hospital
      summary: 病院情報を取得
      operationId: 3a01b01dd95e29de3eb73a0f487a9cdf
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response~1Hospital'
    put:
      tags:
        - Hospital
      summary: 病院情報を更新
      operationId: 256b677b9da1cf3e8ca8b69659c910da
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Requests~1Hospital~1HospitalSaveRequest'
      responses:
        '200':
          description: 成功
        '422':
          description: バリデーションエラー
  /hospital/menus:
    get:
      tags:
        - Hospital
      summary: 診察メニューの一覧
      operationId: c456a36de2619e061663dc8aedbea58b
      parameters:
        -
          name: page
          in: query
          description: ページ番号
        -
          name: per_page
          in: query
          description: 1ページあたりの表示数（デフォルト50件）
        -
          name: sort
          in: query
          description: 並び替え
          example:
            - name
            - '-detail'
        -
          name: keyword
          in: query
          description: 検索キーワード（メニュー名または説明の部分一致）
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response~1Hospital'
  '/hospital/menus/{uuid}':
    get:
      tags:
        - Hospital
      summary: 診察メニューの詳細
      operationId: 22cab2c12d92e3e1e54720ffe674e6d9
      parameters:
        -
          name: uuid
          in: path
          description: 診察メニューID
          example: 1667cff9-71e5-4719-953c-e074507d2d3d
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response~1Menu'
components:
  schemas:
    Requests/Hospital/HospitalSaveRequest:
      description: 病院情報の保存
      required:
        - name
        - zipcode
        - address
        - phone
        - is_published
      properties:
        name:
          description: 病院名
          type: string
          example: テスト病院
        zipcode:
          description: '郵便番号 (7桁)'
          type: string
          example: 1234567
        address:
          description: 住所
          type: string
          example: 東京都新宿区西新宿2-8-1
        phone:
          description: '電話番号 (10または11桁)'
          type: string
          example: '0123456789'
        is_published:
          description: 公開状態
          type: boolean
          example: true
      type: object
    Requests/Hospital/LoginRequest:
      description: 病院スタッフログイン
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: staff+1@example.com
        password:
          type: string
          format: password
          example: password
      type: object
    Response/Hospital:
      description: 病院情報
      properties:
        uuid:
          description: 病院ID
          type: string
          example: e23c0dce-5d69-4572-a283-3643d69350bc
        name:
          description: 病院名
          type: string
          example: テスト病院
        zipcode:
          description: 郵便番号
          type: string
          example: '1234567'
        address:
          description: 住所
          type: string
          example: 山梨県工藤市南区津田町加藤5-1-5
        phone:
          description: 電話番号
          type: string
          example: '0123456789'
        is_published:
          description: 公開フラグ
          type: boolean
          example: true
      type: object
    Response/Menu:
      description: 診察メニュー
      properties:
        uuid:
          description: 診察メニューID
          type: string
          example: 1667cff9-71e5-4719-953c-e074507d2d3d
        name:
          description: 診察メニュー名
          type: string
          example: 一般診察
        detail:
          description: 説明
          type: string
          example: 基本的な診察を行います。健康状態のチェックや病気の早期発見をサポートします。
        required_time:
          description: 所要時間（分）
          type: string
          example: '30'
        is_published:
          description: 公開フラグ
          type: boolean
          example: true
      type: object
tags:
  -
    name: Hospital
    description: 病院スタッフ
