name: Test

on:
  push:
    branches:
      - develop
    paths:
      - src/**/*.php
  pull_request:
    branches:
      - develop
    paths:
      - src/**/*.php

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Setup .env
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Get PHP version
        run: php --version && php artisan --version

      - name: Run Tests
        run: php artisan test
